russian_memo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import index
from words.views import cards, fetch_cards

app_name = 'main'
name_space = 'main'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account',)),
    path('words/', include('words.urls', namespace='words',)),
    path('games/', include('memorisation.urls')),

    path('', index,  name='home'),
    path('api/cards/', cards, name='cards'),
    path('fetch/', fetch_cards, name='fetch_cards'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

words/urls.py
from django.urls import path

from .views import (CardCreateView, DeckListView, CardListView, DeckUpdateView,
                    CardUpdateView, CardDeleteView, DeckDeleteView, deck_create)

app_name = 'words'

urlpatterns = [
    path('decks/add/', deck_create, name='deck_add'),
    path('decks/', DeckListView.as_view(), name='deck_list'),
    path('<int:pk>/cards/', CardListView.as_view(), name='card_list'),
    path('<int:pk>/cards/add/', CardCreateView.as_view(), name='card_add'),
    path('decks/<int:pk>/', DeckUpdateView.as_view(), name='deck_update'),
    path('cards/<int:pk>/', CardUpdateView.as_view(), name='card_update'),
    path('cards/<int:pk>/delete/', CardDeleteView.as_view(), name='card_delete'),
    path('decks/<int:pk>/delete/', DeckDeleteView.as_view(), name='deck_delete'),
]

words/models.py
from django.db import models
from account.models import User


class Deck(models.Model):
    category = models.CharField(max_length=100, default="New Deck")
    color = models.CharField(default="#00bcd4", max_length=30)
    student = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='decks')

    def __str__(self):
        return self.category


class Card(models.Model):
    deck = models.ForeignKey(
        Deck, on_delete=models.CASCADE, related_name='cards')
    word = models.CharField(max_length=100, blank=False, null=False)
    image = models.ImageField(upload_to='cards/', blank=True)
    explanation = models.TextField(max_length=500, blank=True)
    translation = models.CharField(max_length=55, blank=True)
    synonymes = models.TextField(max_length=255, blank=True)

    def __str__(self):
        return self.word

words/views.py
from django.shortcuts import render, redirect, reverse
from django.core.serializers import serialize
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, UpdateView, DeleteView


from .models import Card, Deck
from memorisation.models import Practice
from account.decorators import teacher_required, student_required


@login_required
def deck_create(request):
    if request.method == "POST":
        category = request.POST['category']
        color = request.POST['color']
        student = request.user

        deck = Deck(student=student, category=category, color=color)
        deck.save()
        messages.success(request, "Deck created!")
        return redirect('words:deck_list')

    return render(request, 'words/deck_add.html')


@method_decorator([login_required, student_required], name='dispatch')
class DeckListView(ListView):
    model = Deck
    template_name = 'words/deck_list.html'

    def get_queryset(self):
        queryset = Deck.objects.filter(student=self.request.user)
        return queryset


@method_decorator([login_required], name='dispatch')
class CardListView(ListView):
    model = Card
    template_name = 'words/card_list.html'
    pk_url_kwarg = 'pk'

    def get_context_data(self):
        deck_id = self.kwargs['pk']
        context = {
            'pk': deck_id,
            'cards': Card.objects.filter(deck_id=deck_id)
        }
        return context


@method_decorator([login_required], name='dispatch')
class CardCreateView(CreateView):
    model = Card
    fields = ('word', 'explanation', 'translation', 'synonymes', )
    template_name = 'words/card_add.html'

    def form_valid(self, form):
        card = form.save(commit=False)

        deck_id = self.kwargs['pk']
        card.deck = Deck.objects.get(pk=deck_id)
        card.save()

        practice = Practice(card=card)
        practice.save()

        messages.success(self.request, "Card created!")
        return redirect('words:card_list', deck_id)


@method_decorator([login_required], name='dispatch')
class DeckUpdateView(UpdateView):
    model = Deck
    fields = ('category', 'color', )
    context_object_name = 'deck'
    template_name = 'words/deck_update.html'

    def get_queryset(self):
        return self.request.user.decks.all()

    def get_success_url(self):
        messages.success(self.request, "Deck updated!")
        return reverse('words:deck_update', kwargs={'pk': self.object.pk})


@method_decorator([login_required], name='dispatch')
class CardUpdateView(UpdateView):
    model = Card
    fields = ('word', 'explanation', 'translation',  'synonymes')
    context_object_name = 'card'
    template_name = 'words/card_update.html'

    def get_queryset(self):
        queryset = Card.objects.filter(pk=self.kwargs['pk'])
        return queryset

    def get_success_url(self):
        messages.success(self.request, "Card updated!")
        return reverse('words:card_update', kwargs={'pk': self.object.pk})


@method_decorator([login_required], name='dispatch')
class CardDeleteView(DeleteView):
    model = Card
    context_object_name = 'card'
    template_name = 'words/card_delete_confirm.html'
    pk_url_kwarg = 'pk'

    def delete(self, request, *args, **kwargs):
        card = self.get_object()
        messages.success(
            request, 'The card %s was deleted with success!' % card.word)
        return super().delete(request, *args, **kwargs)

    def get_queryset(self):
        queryset = Card.objects.filter(pk=self.kwargs['pk'])
        return queryset

    def get_success_url(self):
        messages.error(self.request, "Card deleted.")
        return reverse('words:deck_list')


@method_decorator([login_required], name='dispatch')
class DeckDeleteView(DeleteView):
    model = Deck
    context_object_name = 'deck'
    template_name = 'words/deck_delete_confirm.html'
    pk_url_kwarg = 'pk'

    def delete(self, request, *args, **kwargs):
        deck = self.get_object()
        messages.success(
            request, 'The deck %s was deleted with success!' % deck.category)
        return super().delete(request, *args, **kwargs)

    def get_queryset(self):
        queryset = Deck.objects.filter(pk=self.kwargs['pk'])
        return queryset

    def get_success_url(self):
        messages.error(self.request, "Deck deleted.")
        return reverse('words:deck_list')


def cards(request):
    queryset = Card.objects.all()
    queryset = serialize('json', queryset)
    return HttpResponse(queryset, content_type="application/json")


@login_required
def fetch_cards(request):
    return render(request, 'games/fetch_test.html')

templates/words/card_add.html
{% extends 'base.html' %}


{% block content %}
<h2 class="mb-3">Add a new Card</h2>
<form method="post" novalidate>
    <div class="card-panel">
        {% csrf_token %}
        {% for field in form %}
        {% for error in field.errors %}
        <material-toast message="{{error}}" color="red"></material-toast>
        {% endfor %}
        <div class="input-field mb-2">
            {{ field}}
            <label for="{{ field.id_for_label }}">{{ field.html_name }}</label>
        </div>
        {% endfor %}
        <button type="submit" class="btn-floating btn-large indigo ">
            <i class=" material-icons ">add</i>
        </button>
    </div>
</form>
{% endblock %}

templates/words/card_delete_confirm.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<h2 class="mb-3">Confirm deletion</h2>
<p class="flow-tex">
    Are you sure you want to delete the card <strong>"{{ card.word }}"</strong>? There is no
    going back.
</p>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn red ">Yes, I'm sure</button>
    <a href="{% url 'words:card_update' card.id %}" class="btn blue-grey" role="button">Nevermind</a>
</form>
{% endblock %}

templates/words/card_list.html
{% extends 'base.html' %}
{% block content %}

<div class="row">
    {% for card in cards %}
    <div class="col s12 m4">
        <div class="card-panel" style="background-color: {{card.deck.color}};">
            <a href="{% url 'words:card_update' card.id %}">
                <h3 class="white-text center">{{ card.word}}</h3>
            </a>
        </div>
    </div>
    {% empty %}
    <p class=" flow-text center"> You have no Cards in this Deck</p>
    {% endfor %}

    <div class="fixed-action-btn">
        <a href="{% url 'words:card_add' pk %}" class="btn-floating btn-large waves-effect waves-light indigo">
            <i class="material-icons">add</i>
        </a>
    </div>
</div>

{% endblock %}

templates/words/card_update.html
{% extends 'base.html' %}


{% block content %}
<h2 class="mb-3">{{card.word}}</h2>
<form method="post" novalidate>
    <div class="card-panel">
        {% csrf_token %}
        {% for field in form %}
        {% for error in field.errors %}
        <material-toast message="{{error}}" color="red"></material-toast>
        {% endfor %}
        <div class="input-field mb-2">
            {{field}}
            <label for="{{ field.id_for_label }}">{{ field.html_name }}</label>
        </div>
        {% endfor %}
        <button type="submit" class="btn-floating btn-large teal ">
            <i class=" material-icons ">save</i>
        </button>
        <a href="{% url 'words:card_delete' card.id %}" class="btn-floating btn-large red right">
            <i class=" material-icons ">delete</i>
        </a>
    </div>
</form>
{% endblock %}

templates/words/deck_add.html
{% extends 'base.html' %}

{% block content %}

<a href="{% url 'words:deck_list' %}" type="submit" class="btn blue-grey">
    <i class="material-icons left">arrow_back</i>
    Back
</a href="">
<h2 class="mb-3">Add a new Deck</h2>
<form method="POST" class=" card-panel">
    {% csrf_token %}
    <div class=" input-field">
        <input id="category" name='category' type="text" value="New Deck" class="">
        <label for="category">Category</label>
    </div>
    <div class="" style="margin-bottom: 2rem;">
        <label for="color">Color</label>
        <input type="color" name="color" id="color">

    </div>
    <button type="submit" class="btn ">
        <i class="material-icons left">save</i>
        Save
    </button>
</form>

{% endblock %}

templates/words/deck_delete_confirm.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<h2 class="mb-3">Confirm deletion</h2>
<p class="flow-tex">
    Are you sure you want to delete the Deck <strong>"{{ deck.category }}"</strong>? There is no
    going back.
</p>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn red ">Yes, I'm sure</button>
    <a href="{% url 'words:deck_update' deck.id %}" class="btn " role="button">Nevermind</a>
</form>
{% endblock %}

templates/words/deck_list.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    {% for deck in object_list %}
    <div class="col s12 m4">
        <div class="card-panel" style="background-color: {{deck.color}};">
            <a href="{% url 'words:card_list' deck.id %}">
                <h3 class="white-text center">{{ deck.category}}</h3>
            </a>
        </div>
    </div>
    {% empty %}
    <p class="flow-text center"> You have no Deck</p>
    {% endfor %}
</div>
<div class="fixed-action-btn">
    <a href="{% url 'words:deck_add' %}" class="btn-floating btn-large waves-effect waves-light indigo">
        <i class="material-icons">add</i>
    </a>
</div>

{% endblock %}

templates/words/deck_update.html
{% extends 'base.html' %}
{% block content %}
<h2 class="mb-3">
    {{ deck.category }}

</h2>
<div class="row mb-3">
    <div class="col-md-6 col-sm-8 col-12">
        <form method="post" novalidate>
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn green">Save changes</button>
            <a href="#" class="btn btn-outline-secondary" role="button">Nevermind</a>
            <a href="{% url 'words:deck_delete' deck.id %}" class="btn red float-right">Delete</a>
        </form>
    </div>
</div>
{% endblock %}