memorisation/urls.py
from django.urls import path

from .views import hangman, speed_typing, next_practice_item, process_rating

app_name = 'memo'


urlpatterns = [
    path('hangman/', hangman, name='hangman'),
    path('translate/', speed_typing, name='speed_typing'),
    path('flashcards/', next_practice_item, name='flashcards'),
    path('process_rating/', process_rating, name='process_rating'),
]

russian_memo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import index
from words.views import cards, fetch_cards

app_name = 'main'
name_space = 'main'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account',)),
    path('words/', include('words.urls', namespace='words',)),
    path('games/', include('memorisation.urls')),

    path('', index,  name='home'),
    path('api/cards/', cards, name='cards'),
    path('fetch/', fetch_cards, name='fetch_cards'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

words/urls.py
from django.urls import path

from .views import (CardCreateView, DeckListView, CardListView, DeckUpdateView,
                    CardUpdateView, CardDeleteView, DeckDeleteView, deck_create)

app_name = 'words'

urlpatterns = [
    path('decks/add/', deck_create, name='deck_add'),
    path('decks/', DeckListView.as_view(), name='deck_list'),
    path('<int:pk>/cards/', CardListView.as_view(), name='card_list'),
    path('<int:pk>/cards/add/', CardCreateView.as_view(), name='card_add'),
    path('decks/<int:pk>/', DeckUpdateView.as_view(), name='deck_update'),
    path('cards/<int:pk>/', CardUpdateView.as_view(), name='card_update'),
    path('cards/<int:pk>/delete/', CardDeleteView.as_view(), name='card_delete'),
    path('decks/<int:pk>/delete/', DeckDeleteView.as_view(), name='deck_delete'),
]

templates/games/fetch_test.html
{% extends 'base.html' %}

{% block content %}
<div id="output"></div>

<script>
    function getCards() {
        fetch("http://127.0.0.1:8000/api/cards/")
            .then((res) => res.json())
            .then((data) => {
                let output = "<h2>Cards</h2>"
                console.log(data)
                data.forEach(card => {
                    output += `
                   <ul class="collection">
                       <li class="collection-item">id: ${card.pk}<li>
                        <li class="collection-item">word: ${card.fields.word} <li>
                   </ul>
                   `

                })
                document.querySelector("#output").innerHTML = output;
            })
    }
    getCards()
</script>
{% endblock %}

templates/games/flashcards.html
{% load humanize %} {% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{%  static 'css/materialize.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/flashcards.css' %}" />
    <link
      href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet"
    />

    <title>Flip Card</title>
  </head>

  <body class="bg-primary">
    {% include 'layout/_navbar.html' %}

    <div class="container">
      <div class="center">
        {% if practice %}
        <div class="card-container">
          <div class="card white-text z-depth-3" id="flashcard">
            <!-- 	Front	  -->
            <figure class="front card-content white black-text center">
              <h4>{{card.translation}}</h4>
            </figure>
            <!-- 	Back	 -->
            <figure class="back card-content white black-text">
              <h4>{{card.word}}</h4>
              <div class="divider"></div>
              <p>
                <strong>explanation</strong><br />
                {{card.explanation}}
              </p>
              <p>
                <strong>translation</strong> : <br />
                {{card.translation}}.
              </p>
              <p>
                <strong>synonyms</strong> : <br />
                {{card.synonymes}}.
              </p>
            </figure>
          </div>
          <button class="btn btn-large bg-secondary" id="flip-btn">Flip</button>
          <form
            class="hide"
            action="{% url 'memo:process_rating' %}"
            method="post"
          >
            {% csrf_token %} {{form}}
            <input type="submit" value="submit" class="btn bg-secondary" />
          </form>
          <h4>{{ practice.next_practice }}</h4>
        </div>
        {% else %}
        <p class="flow-text">
          You don't have cards to practice today. <br />
          Next practice {{ next_practice|naturalday }}.
        </p>
        {% endif %}
      </div>
    </div>
  </body>
  <script src="{% static 'js/materialize.min.js' %}"></script>
  <script src="{% static 'js/flashcards.js' %}"></script>
</html>

templates/games/hangman.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Hangman Game</title>
    <link rel="stylesheet" href="{% static 'css/materialize.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/hangman.css' %}" />
    <link
      href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet"
    />
  </head>

  <body class="bg-primary white-text">
    {% include 'layout/_navbar.html' %}

    <div class="bg-primary white-text container">
      <h3>Hangman Game</h3>
      <p>Find the hidden word - Enter a letter</p>
      <div class="game-container">
        <svg height="250" width="200" class="figure-container">
          <!--  Rod  -->
          <line x1="60" y1="20" x2="140" y2="20" />
          <line x1="60" y1="20" x2="60" y2="230" />
          <line x1="140" y1="20" x2="140" y2="50" />
          <line x1="30" y1="230" x2="90" y2="230" />
          <!-- Head -->
          <circle cx="140" cy="70" r="20" class="figure-part" />
          <!-- Body -->
          <line x1="140" y1="90" x2="140" y2="150" class="figure-part" />
          <!-- Arms -->
          <line x1="140" y1="120" x2="120" y2="100" class="figure-part" />
          <line x1="140" y1="120" x2="160" y2="100" class="figure-part" />
          <!-- Legs -->
          <line x1="140" y1="150" x2="120" y2="180" class="figure-part" />
          <line x1="140" y1="150" x2="160" y2="180" class="figure-part" />
        </svg>
        <div class="wrong-letters-container">
          <div id="wrong-letters"></div>
        </div>

        <div class="word" id="word"></div>
      </div>
      <div class="popup-container">
        <div class="popup card">
          <div class="card-content">
            <h3 id="final-message">You have Won &#128515;</h3>
            <a href="{% url 'memo:hangman' %}" class="btn" id="play-btn">
              <i class="material-icons">replay</i>
              Play Again
            </a>
          </div>
        </div>
      </div>
      <div class="notification center-align">
        <p>You have already entered this letter</p>
      </div>
    </div>
    {% include 'layout/_footer.html' %}
  </body>
  <script src="{% static 'js/hangman.js' %}"></script>
  <script src="{% static 'js/materialize.min.js' %}"></script>
</html>

templates/games/speed_typing.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Speed Typing Game</title>
    <link rel="stylesheet" href="{% static 'css/materialize.min.css' %}" />
    <link
      href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet"
    />

    <link rel="stylesheet" href="{% static 'css/speed_typing.css' %}" />
  </head>

  <body class="bg-primary">
    {% include 'layout/_navbar.html' %}
    <div class="center-align container">
      <!-- Word & Input -->

      <p class="flow-text font-weight-bold">
        Type The Translation Of This Word Within
        <strong class="yellow-text" id="seconds"></strong> Seconds:
      </p>
      <div class="row my-3 valign-wrapper">
        <div class="col s9">
          <h2 class="display-3 mb-5 font-weight-bold" id="current-word"></h2>
        </div>
        <div class="col s3 valign-wrapper right">
          <i class="material-icons medium right" id="speaker">volume_up</i>
        </div>
      </div>
      <input
        type="text"
        class="white-text"
        placeholder="Start typing..."
        id="word-input"
      />
      <h4 class="mt-3 yellow-text" id="message"></h4>

      <!-- Time & Score Columns -->
      <div class="row mt-5">
        <div class="col m6">
          <h4>
            Time Left:
            <span id="time">0</span>
          </h4>
        </div>
        <div class="col m6">
          <h4>
            Score:
            <span id="score">0</span>
          </h4>
        </div>
      </div>

      <!-- Instructions -->
      <div class="row mt-5">
        <div class="col-md-12">
          <div class="card-panel bg-secondary black-text font-weight-bold mb-5">
            <h5>Instructions</h5>
            <p>
              Type the translation of each word in the given amount of seconds
              to score. To play again, just type the current word. Your score
              will reset
            </p>
          </div>
        </div>
      </div>
    </div>
    <!-- Pop up -->
    <div class="popup-container">
      <div class="popup card indigo">
        <div class="card-content">
          <h3 id="final-message">Unfortunatly you lost &#128531;</h3>
          <a href="{% url 'memo:speed_typing' %}" class="btn" id="play-btn">
            <i class="material-icons">replay</i>
            Play Again
          </a>
        </div>
      </div>
    </div>
    <script src="{% static 'js/speed_typing.js' %}"></script>
    <script src="{% static 'js/materialize.min.js' %}"></script>
  </body>
</html>