account/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView

from .views import (StudentSignUpView, TeacherSignUpView, logout,
                    login, dashboard, )

app_name = 'account'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('dashboard/', dashboard, name="dashboard"),
    path('student_registration/', StudentSignUpView.as_view(),
         name='student_registration'),
    path('teacher_registration/', TeacherSignUpView.as_view(),
         name='teacher_registration'),
]

memorisation/urls.py
from django.urls import path

from .views import hangman, speed_typing, next_practice_item, process_rating

app_name = 'memo'


urlpatterns = [
    path('hangman/', hangman, name='hangman'),
    path('translate/', speed_typing, name='speed_typing'),
    path('flashcards/', next_practice_item, name='flashcards'),
    path('process_rating/', process_rating, name='process_rating'),
]

russian_memo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import index
from words.views import cards, fetch_cards

app_name = 'main'
name_space = 'main'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account',)),
    path('words/', include('words.urls', namespace='words',)),
    path('games/', include('memorisation.urls')),

    path('', index,  name='home'),
    path('api/cards/', cards, name='cards'),
    path('fetch/', fetch_cards, name='fetch_cards'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

words/urls.py
from django.urls import path

from .views import (CardCreateView, DeckListView, CardListView, DeckUpdateView,
                    CardUpdateView, CardDeleteView, DeckDeleteView, deck_create)

app_name = 'words'

urlpatterns = [
    path('decks/add/', deck_create, name='deck_add'),
    path('decks/', DeckListView.as_view(), name='deck_list'),
    path('<int:pk>/cards/', CardListView.as_view(), name='card_list'),
    path('<int:pk>/cards/add/', CardCreateView.as_view(), name='card_add'),
    path('decks/<int:pk>/', DeckUpdateView.as_view(), name='deck_update'),
    path('cards/<int:pk>/', CardUpdateView.as_view(), name='card_update'),
    path('cards/<int:pk>/delete/', CardDeleteView.as_view(), name='card_delete'),
    path('decks/<int:pk>/delete/', DeckDeleteView.as_view(), name='deck_delete'),
]

templates/layout/_footer.html
<style>
  html,
  body {
    height: 100%;
  }
  .container {
    min-height: 100%;
  }

  .footer {
    position: relative;
    height: 50px;
    margin-top: 50px;
    clear: both;
  }
</style>

<footer class="page-footer black" style="padding-top: 0; margin-top: 3rem;">
  <div class="footer-copyright">
    <div class="container center">
      &copy; <span id="copyright-year">2020</span> Copyright
    </div>
  </div>
</footer>

<script>
  const year = new Date();
  document.querySelector('#copyright-year').textContent = year.getFullYear();
</script>

templates/layout/_navbar.html
{% load memorisation_extras %}
<ul id="dropdown1" class="dropdown-content bg-primary">
  <li><a href="{% url 'memo:hangman' %}">Hangman</a></li> 
  <li class="divider"></li>
  <li><a href="{% url 'memo:speed_typing' %}">Speed Typing</a></li>
</ul>
{% if request.path == '/' %}
  <nav class="transparent">
{% else %}
  <nav class="bg-primary">
{% endif %}
    <div class="nav-wrapper">
      <div class="container">
        <a href="#" class="brand-logo"> Memo</a>
        <a href="#" class="sidenav-trigger" data-target="mobile-nav">
          <i class="material-icons">menu</i>
        </a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><a href="{% url 'home' %}">Home</a></li>
        {% if request.user.is_authenticated %} 
          {% if request.user.is_student %}
          <li>
            <a href="{% url 'words:deck_list' %}"> Decks</a>
          </li>
          <li>
            <a href="{% url 'memo:flashcards' %}">
              Flash Cards 
              <span class="badge bg-secondary text-white">{% to_practice request.user %}</span>
            </a>
          </li>
          <li>
            <a class="dropdown-trigger" href="#!" data-target="dropdown1"
              >Games<i class="material-icons right">arrow_drop_down</i></a
            >
          </li>

          {% endif %}

          <li>
            <a
              href="{% url 'account:logout' %}"
              class="waves-effect waves-light btn bg-secondary"
              >Log out
              <i class="material-icons right">exit_to_app</i>
            </a>
          </li>
        {% else %}
          <li>
            <a href="{% url 'account:student_registration' %}"
              >Student Signup</a
            >
          </li>
          <li>
            <a href="{% url 'account:teacher_registration' %}"
              >Teacher Signup</a
            >
          </li>
          <li><a href="{% url 'account:login' %}">Sign In</a></li>

        {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <!-- Side Nav -->
  <ul class="sidenav" id="mobile-nav">
    <li>
      <h4 class="deep-purple-text center">Russian Memo</h4>
    </li>
    <li>
      <div class="divider"></div>
    </li>
    <li>
      <a href="{% url 'home' %}" class="black-text">
        <i class="material-icons black-text">home</i>Home
      </a>
    </li>
    {% if request.user.is_authenticated %}
    <li>
      <a href="{% url 'account:dashboard' %}" class="black-text">
        <i class="material-icons black-text">dashboard</i>
        Dashboard
      </a>
    </li>
    <li>
      <a href="{% url 'account:logout' %}" class="black-text">
        <i class="material-icons black-text">exit_to_app</i>
        Logout
      </a>
    </li>
    {% else %}
    <li>
      <a href="{% url 'account:student_registration' %}" class="black-text">
        <i class="material-icons black-text">event_seat</i> Student Registration
      </a>
    </li>
    <li>
      <a href="{% url 'account:teacher_registration' %}" class="black-text">
        <i class="material-icons black-text">event_seat</i> Teacher Registration
      </a>
    </li>
    <li>
      <a href="{% url 'account:login' %}" class="black-text">
        <i class="material-icons black-text">event_seat</i> Sign In
      </a>
    </li>
    {% endif %}
  </ul>

  <script>
    document.addEventListener('DOMContentLoaded', function () {
      const sideNav = document.querySelector('.sidenav');
      M.Sidenav.init(sideNav, {
        menuWidth: 100,
      });

      const dropDown = document.querySelectorAll('.dropdown-trigger');
      M.Dropdown.init(dropDown);
    });
  </script>
</nav>

templates/layout/_toast.html
{% if messages %}
{% for message in messages %}
<!-- INFO -->
{% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
<material-toast message="{{ message }}" color="cyan"></material-toast>
{% endif %}
<!-- SUCCESS -->
{% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
<material-toast message="{{ message }}" color="green"></material-toast>
{% endif %}
<!-- WARNING -->
{% if message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
<material-toast message="{{ message }}" color="yellow"></material-toast>
{% endif %}
<!-- ERROR -->
{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
<material-toast message="{{ message }}" color="red"></material-toast>
{% endif %}

{% endfor %}
{% endif %}

<script>
    // Custom Elements
    class Toast extends HTMLElement {
        constructor() {
            super();
            this.message = this.getAttribute('message');
            this.color = this.getAttribute('color');
            this.init = M.toast({
                html: this.message,
                classes: `rounded ${this.color}`
            });

        }

    }

    customElements.define('material-toast', Toast);

</script>